from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "v2_all_domains"
down_revision = "v1_iam_create_tables"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS sys")
    op.execute("CREATE SCHEMA IF NOT EXISTS pdm")
    op.execute("CREATE SCHEMA IF NOT EXISTS som")
    op.execute("CREATE SCHEMA IF NOT EXISTS oms")
    op.execute("CREATE SCHEMA IF NOT EXISTS scm")
    op.execute("CREATE SCHEMA IF NOT EXISTS wms")
    op.execute("CREATE SCHEMA IF NOT EXISTS tms")
    op.execute("CREATE SCHEMA IF NOT EXISTS fms")

    op.create_table("outbox_message",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("event_id", sa.String(36), nullable=False, index=True),
        sa.Column("event_type", sa.String(200), nullable=False, index=True),
        sa.Column("event_version", sa.String(10), nullable=False, server_default="v1"),
        sa.Column("aggregate_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("aggregate_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("payload", sa.Text, nullable=False, server_default="{}"),
        sa.Column("payload_hash", sa.String(64), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("retry_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("max_retries", sa.Integer, nullable=False, server_default="3"),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("idempotency_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("idempotency_key", sa.String(200), nullable=False, unique=True, index=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("request_hash", sa.String(64), nullable=False, server_default=""),
        sa.Column("response_data", sa.Text, nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="completed"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("recommendation",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(100), nullable=False, index=True),
        sa.Column("erp_reference_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("recommendation_type", sa.String(50), nullable=False),
        sa.Column("target_object_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("target_object_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("content_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("score", sa.Float, nullable=False, server_default="0"),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("evidence_chain_id", sa.String(100), nullable=False, server_default=""),
        sa.Column("data_sources_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("risk_flags_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("explainability", sa.Text, nullable=False, server_default=""),
        sa.Column("requested_action", sa.String(100), nullable=False, server_default=""),
        sa.Column("approval_policy", sa.String(50), nullable=False, server_default="manual"),
        sa.Column("status", sa.String(30), nullable=False, server_default="submitted", index=True),
        sa.Column("rejection_reason", sa.Text, nullable=False, server_default=""),
        sa.Column("execution_result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("measured_result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("idempotency_key", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("source_system", sa.String(30), nullable=False, server_default="PMS"),
        sa.Column("actor_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("actor_type", sa.String(30), nullable=False, server_default="service_account"),
        sa.Column("agent_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("scope", sa.String(200), nullable=False, server_default=""),
        sa.Column("purpose", sa.String(200), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("draft_document",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(36), nullable=False, index=True),
        sa.Column("draft_type", sa.String(50), nullable=False),
        sa.Column("draft_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("converted_to", sa.String(36), nullable=False, server_default=""),
        sa.Column("idempotency_key", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("pending_action",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(36), nullable=False, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("action_type", sa.String(50), nullable=False),
        sa.Column("action_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("idempotency_key", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("risk_alert",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("risk_type", sa.String(50), nullable=False),
        sa.Column("risk_level", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("evidence_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="open", index=True),
        sa.Column("assigned_to", sa.String(36), nullable=False, server_default=""),
        sa.Column("resolution", sa.Text, nullable=False, server_default=""),
        sa.Column("idempotency_key", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("insight_card",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("card_type", sa.String(50), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("content_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("metrics_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idempotency_key", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("approval_flow_definition",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("flow_code", sa.String(100), nullable=False),
        sa.Column("flow_name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("target_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("nodes_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("approval_instance",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("flow_id", sa.String(36), nullable=False),
        sa.Column("flow_code", sa.String(100), nullable=False, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("target_type", sa.String(100), nullable=False),
        sa.Column("target_id", sa.String(36), nullable=False, index=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("current_node_index", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("submitted_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("approval_task",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("instance_id", sa.String(36), nullable=False, index=True),
        sa.Column("node_id", sa.String(50), nullable=False),
        sa.Column("node_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("assignee_id", sa.String(36), nullable=False, index=True),
        sa.Column("assignee_role_code", sa.String(80), nullable=False, server_default=""),
        sa.Column("action", sa.String(20), nullable=True),
        sa.Column("comment", sa.Text, nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("delegated_from", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        schema="sys"
    )

    op.create_table("category",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("parent_id", sa.String(36), nullable=True, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("path", sa.String(500), nullable=False, server_default=""),
        sa.Column("level", sa.Integer, nullable=False, server_default="1"),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="pdm"
    )

    op.create_table("brand",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("name_en", sa.String(200), nullable=False, server_default=""),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("logo_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="pdm"
    )

    op.create_table("spu",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("name_en", sa.String(500), nullable=False, server_default=""),
        sa.Column("code", sa.String(100), nullable=False, unique=True),
        sa.Column("category_id", sa.String(36), nullable=True, index=True),
        sa.Column("brand_id", sa.String(36), nullable=True, index=True),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("description_en", sa.Text, nullable=False, server_default=""),
        sa.Column("main_image", sa.String(500), nullable=False, server_default=""),
        sa.Column("images_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("attributes_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("spu_type", sa.String(30), nullable=False, server_default="normal"),
        sa.Column("origin_country", sa.String(50), nullable=False, server_default=""),
        sa.Column("hs_code", sa.String(30), nullable=False, server_default=""),
        sa.Column("declared_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("declared_currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="pdm"
    )

    op.create_table("sku",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("spu_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_code", sa.String(100), nullable=False, index=True),
        sa.Column("barcode", sa.String(50), nullable=False, server_default=""),
        sa.Column("name", sa.String(500), nullable=False, server_default=""),
        sa.Column("variant_attrs_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("spec_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("length", sa.Float, nullable=False, server_default="0"),
        sa.Column("width", sa.Float, nullable=False, server_default="0"),
        sa.Column("height", sa.Float, nullable=False, server_default="0"),
        sa.Column("cost_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("cost_currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("purchase_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("supplier_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("image", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="pdm"
    )

    op.create_table("channel_sku_mapping",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("channel", sa.String(50), nullable=False, index=True),
        sa.Column("channel_sku", sa.String(200), nullable=False),
        sa.Column("channel_product_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("store_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="pdm"
    )

    op.create_table("product_project",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("category_id", sa.String(36), nullable=True),
        sa.Column("stage", sa.String(30), nullable=False, server_default="proposing", index=True),
        sa.Column("priority", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("owner_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("team_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("target_market", sa.String(200), nullable=False, server_default=""),
        sa.Column("target_platform", sa.String(200), nullable=False, server_default=""),
        sa.Column("research_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("spu_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="pdm"
    )

    op.create_table("quality_standard",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("category_id", sa.String(36), nullable=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("standard_type", sa.String(50), nullable=False, server_default="general"),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("logistics_attrs_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("packaging_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="pdm"
    )

    op.create_table("ip_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=True, index=True),
        sa.Column("spu_id", sa.String(36), nullable=True, index=True),
        sa.Column("ip_type", sa.String(30), nullable=False),
        sa.Column("ip_number", sa.String(100), nullable=False, server_default=""),
        sa.Column("ip_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("risk_level", sa.String(20), nullable=False, server_default="none"),
        sa.Column("notes", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="pdm"
    )

    op.create_table("sensitive_word",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("word", sa.String(200), nullable=False),
        sa.Column("word_type", sa.String(30), nullable=False, server_default="general"),
        sa.Column("language", sa.String(10), nullable=False, server_default="en"),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="pdm"
    )

    op.create_table("upc_pool",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("upc_code", sa.String(50), nullable=False, unique=True),
        sa.Column("sku_id", sa.String(36), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="available", index=True),
        sa.Column("allocated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="pdm"
    )

    op.create_table("store",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("region", sa.String(50), nullable=False, server_default=""),
        sa.Column("store_id_on_platform", sa.String(200), nullable=False, server_default=""),
        sa.Column("seller_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("auth_status", sa.String(20), nullable=False, server_default="unauthorized"),
        sa.Column("auth_token_encrypted", sa.Text, nullable=False, server_default=""),
        sa.Column("auth_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="som"
    )

    op.create_table("listing",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("channel_sku", sa.String(200), nullable=False, server_default=""),
        sa.Column("platform_listing_id", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("title", sa.String(1000), nullable=False, server_default=""),
        sa.Column("title_en", sa.String(1000), nullable=False, server_default=""),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("bullet_points_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("search_terms", sa.String(500), nullable=False, server_default=""),
        sa.Column("main_image", sa.String(500), nullable=False, server_default=""),
        sa.Column("images_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("price", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("msrp", sa.Float, nullable=False, server_default="0"),
        sa.Column("sale_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("sale_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sale_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("listing_status", sa.String(30), nullable=False, server_default="not_listed", index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("category_id", sa.String(36), nullable=True),
        sa.Column("is_pms_draft", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="som"
    )

    op.create_table("price_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("rule_type", sa.String(50), nullable=False),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("region", sa.String(50), nullable=False, server_default=""),
        sa.Column("category_id", sa.String(36), nullable=True),
        sa.Column("formula_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("min_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("max_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="som"
    )

    op.create_table("listing_batch_job",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("job_type", sa.String(50), nullable=False),
        sa.Column("total_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("success_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("fail_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="som"
    )

    op.create_table("operation_monitor",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("metric_type", sa.String(50), nullable=False),
        sa.Column("metric_date", sa.DateTime(timezone=True), nullable=False, index=True),
        sa.Column("metrics_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="som"
    )

    op.create_table("sales_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("order_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform_order_id", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("order_type", sa.String(30), nullable=False, server_default="standard"),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("order_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pay_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ship_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("complete_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("buyer_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("buyer_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("recipient_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("recipient_phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("recipient_address", sa.Text, nullable=False, server_default=""),
        sa.Column("recipient_city", sa.String(100), nullable=False, server_default=""),
        sa.Column("recipient_state", sa.String(100), nullable=False, server_default=""),
        sa.Column("recipient_country", sa.String(50), nullable=False, server_default=""),
        sa.Column("recipient_zip", sa.String(30), nullable=False, server_default=""),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("item_subtotal", sa.Float, nullable=False, server_default="0"),
        sa.Column("shipping_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("discount_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("tax_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("settlement_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("warehouse_id", sa.String(36), nullable=True),
        sa.Column("logistics_channel", sa.String(100), nullable=False, server_default=""),
        sa.Column("tracking_no", sa.String(100), nullable=False, server_default=""),
        sa.Column("is_split", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("parent_order_id", sa.String(36), nullable=True),
        sa.Column("is_merged", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("merged_into_id", sa.String(36), nullable=True),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("tags_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("risk_flags_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("raw_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="oms"
    )

    op.create_table("sales_order_item",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("order_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("channel_sku", sa.String(200), nullable=False, server_default=""),
        sa.Column("product_name", sa.String(500), nullable=False, server_default=""),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="1"),
        sa.Column("unit_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("discount_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("item_total", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("platform_item_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="oms"
    )

    op.create_table("refund_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("refund_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("original_order_id", sa.String(36), nullable=False, index=True),
        sa.Column("refund_type", sa.String(30), nullable=False),
        sa.Column("reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("refund_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("platform_refund_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="oms"
    )

    op.create_table("order_split_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("rule_type", sa.String(50), nullable=False),
        sa.Column("conditions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="oms"
    )

    op.create_table("order_audit_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("order_id", sa.String(36), nullable=False, index=True),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("from_status", sa.String(30), nullable=False, server_default=""),
        sa.Column("to_status", sa.String(30), nullable=False, server_default=""),
        sa.Column("operator_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("operator_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="oms"
    )

    op.create_table("supplier",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("short_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("contact_person", sa.String(100), nullable=False, server_default=""),
        sa.Column("contact_phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("contact_email", sa.String(200), nullable=False, server_default=""),
        sa.Column("address", sa.String(500), nullable=False, server_default=""),
        sa.Column("region", sa.String(100), nullable=False, server_default=""),
        sa.Column("supplier_type", sa.String(30), nullable=False, server_default="general"),
        sa.Column("cooperation_level", sa.String(20), nullable=False, server_default="normal"),
        sa.Column("payment_terms", sa.String(100), nullable=False, server_default=""),
        sa.Column("lead_time_days", sa.Integer, nullable=False, server_default="0"),
        sa.Column("min_order_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("quality_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("delivery_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("org_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="scm"
    )

    op.create_table("purchase_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("po_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("supplier_id", sa.String(36), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("po_type", sa.String(30), nullable=False, server_default="standard"),
        sa.Column("status", sa.String(30), nullable=False, server_default="draft", index=True),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("total_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("paid_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("expected_delivery_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_delivery_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="scm"
    )

    op.create_table("purchase_order_item",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("po_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("received_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("unit_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("item_total", sa.Float, nullable=False, server_default="0"),
        sa.Column("expected_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="scm"
    )

    op.create_table("replenishment_plan",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("plan_no", sa.String(100), nullable=False, unique=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("plan_type", sa.String(30), nullable=False, server_default="auto"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="scm"
    )

    op.create_table("supplier_evaluation",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("supplier_id", sa.String(36), nullable=False, index=True),
        sa.Column("period", sa.String(20), nullable=False),
        sa.Column("quality_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("delivery_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("price_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("service_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("overall_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("remarks", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="scm"
    )

    op.create_table("warehouse",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("warehouse_type", sa.String(30), nullable=False, server_default="self"),
        sa.Column("region", sa.String(100), nullable=False, server_default=""),
        sa.Column("address", sa.String(500), nullable=False, server_default=""),
        sa.Column("contact_person", sa.String(100), nullable=False, server_default=""),
        sa.Column("contact_phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("org_id", sa.String(36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="wms"
    )

    op.create_table("location",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("name", sa.String(200), nullable=False, server_default=""),
        sa.Column("zone", sa.String(50), nullable=False, server_default=""),
        sa.Column("aisle", sa.String(20), nullable=False, server_default=""),
        sa.Column("shelf", sa.String(20), nullable=False, server_default=""),
        sa.Column("bin", sa.String(20), nullable=False, server_default=""),
        sa.Column("location_type", sa.String(30), nullable=False, server_default="storage"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("inventory",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("location_id", sa.String(36), nullable=True),
        sa.Column("qty_on_hand", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_reserved", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_available", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_inbound", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_outbound", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_defective", sa.Integer, nullable=False, server_default="0"),
        sa.Column("batch_no", sa.String(100), nullable=False, server_default=""),
        sa.Column("cost_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("cost_currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("last_counted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("inbound_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("inbound_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("inbound_type", sa.String(30), nullable=False, server_default="purchase"),
        sa.Column("source_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("received_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("outbound_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("outbound_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("outbound_type", sa.String(30), nullable=False, server_default="sales"),
        sa.Column("source_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("shipped_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("tracking_no", sa.String(100), nullable=False, server_default=""),
        sa.Column("logistics_channel", sa.String(100), nullable=False, server_default=""),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("stock_movement",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("movement_type", sa.String(30), nullable=False),
        sa.Column("qty_change", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_before", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_after", sa.Integer, nullable=False, server_default="0"),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("location_id", sa.String(36), nullable=True),
        sa.Column("batch_no", sa.String(100), nullable=False, server_default=""),
        sa.Column("operator_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("stock_count",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("count_no", sa.String(100), nullable=False, unique=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("count_type", sa.String(30), nullable=False, server_default="full"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("logistics_provider",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("provider_type", sa.String(30), nullable=False, server_default="express"),
        sa.Column("api_endpoint", sa.String(500), nullable=False, server_default=""),
        sa.Column("api_key_encrypted", sa.Text, nullable=False, server_default=""),
        sa.Column("supported_regions", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="tms"
    )

    op.create_table("shipping_method",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("provider_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False),
        sa.Column("shipping_type", sa.String(30), nullable=False, server_default="standard"),
        sa.Column("estimated_days_min", sa.Integer, nullable=False, server_default="0"),
        sa.Column("estimated_days_max", sa.Integer, nullable=False, server_default="0"),
        sa.Column("first_weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("first_weight_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("additional_weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("additional_weight_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("min_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    )

    op.create_table("shipment",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipment_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("order_id", sa.String(36), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("provider_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipping_method_id", sa.String(36), nullable=False, index=True),
        sa.Column("tracking_no", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("shipping_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("recipient_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("recipient_phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("recipient_address", sa.Text, nullable=False, server_default=""),
        sa.Column("recipient_country", sa.String(50), nullable=False, server_default=""),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("tracking_events_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    )

    op.create_table("freight_template",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("calculation_type", sa.String(30), nullable=False, server_default="by_weight"),
        sa.Column("rules_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    )

    op.create_table("cost_event",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("event_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("cost_type", sa.String(50), nullable=False, index=True),
        sa.Column("amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("exchange_rate", sa.Float, nullable=False, server_default="1"),
        sa.Column("amount_cny", sa.Float, nullable=False, server_default="0"),
        sa.Column("sku_id", sa.String(36), nullable=True, index=True),
        sa.Column("order_id", sa.String(36), nullable=True, index=True),
        sa.Column("shipment_id", sa.String(36), nullable=True, index=True),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("occurred_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="confirmed", index=True),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fms"
    )

    op.create_table("platform_settlement",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("settlement_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("settlement_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("settlement_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_sales", sa.Float, nullable=False, server_default="0"),
        sa.Column("total_refund", sa.Float, nullable=False, server_default="0"),
        sa.Column("platform_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("advertising_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("shipping_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("other_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("net_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("raw_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fms"
    )

    op.create_table("payment_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("payment_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("payment_type", sa.String(30), nullable=False),
        sa.Column("counterparty_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("counterparty_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("payment_method", sa.String(30), nullable=False, server_default="bank_transfer"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fms"
    )

    op.create_table("exchange_rate",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("from_currency", sa.String(10), nullable=False),
        sa.Column("to_currency", sa.String(10), nullable=False),
        sa.Column("rate", sa.Float, nullable=False, server_default="1"),
        sa.Column("rate_date", sa.DateTime(timezone=True), nullable=False, index=True),
        sa.Column("source", sa.String(50), nullable=False, server_default="manual"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fms"
    )


def downgrade() -> None:
    schemas = ["fms", "tms", "wms", "scm", "oms", "som", "pdm"]
    for schema in schemas:
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")

    sys_tables = [
        "approval_task", "approval_instance", "approval_flow_definition",
        "insight_card", "risk_alert", "pending_action", "draft_document",
        "recommendation", "idempotency_record", "outbox_message",
    ]
    for table in sys_tables:
        op.drop_table(table, schema="sys")
