from alembic import op
import sqlalchemy as sa

revision = "v3_ads_crm_fba_bi_dashboard"
down_revision = "v2_all_domains"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS ads")
    op.execute("CREATE SCHEMA IF NOT EXISTS crm")
    op.execute("CREATE SCHEMA IF NOT EXISTS fba")
    op.execute("CREATE SCHEMA IF NOT EXISTS bi")
    op.execute("CREATE SCHEMA IF NOT EXISTS dashboard")

    op.create_table("ad_campaign",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_type", sa.String(30), nullable=False, server_default="sponsored_products"),
        sa.Column("targeting_type", sa.String(30), nullable=False, server_default="manual"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("daily_budget", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_spend", sa.Float, nullable=False, server_default="0"),
        sa.Column("total_sales", sa.Float, nullable=False, server_default="0"),
        sa.Column("total_impressions", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_clicks", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_orders", sa.Integer, nullable=False, server_default="0"),
        sa.Column("acos", sa.Float, nullable=False, server_default="0"),
        sa.Column("roas", sa.Float, nullable=False, server_default="0"),
        sa.Column("platform_campaign_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("is_pms_draft", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("recommendation_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="ads"
    )

    op.create_table("ad_group",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(500), nullable=False),
        sa.Column("default_bid", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="enabled"),
        sa.Column("sku_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("listing_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("platform_ad_group_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ads"
    )

    op.create_table("ad_keyword",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_id", sa.String(36), nullable=False, index=True),
        sa.Column("ad_group_id", sa.String(36), nullable=False, index=True),
        sa.Column("keyword_text", sa.String(500), nullable=False),
        sa.Column("match_type", sa.String(20), nullable=False, server_default="broad"),
        sa.Column("bid", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="enabled"),
        sa.Column("impressions", sa.Integer, nullable=False, server_default="0"),
        sa.Column("clicks", sa.Integer, nullable=False, server_default="0"),
        sa.Column("spend", sa.Float, nullable=False, server_default="0"),
        sa.Column("sales", sa.Float, nullable=False, server_default="0"),
        sa.Column("orders", sa.Integer, nullable=False, server_default="0"),
        sa.Column("ctr", sa.Float, nullable=False, server_default="0"),
        sa.Column("cpc", sa.Float, nullable=False, server_default="0"),
        sa.Column("conversion_rate", sa.Float, nullable=False, server_default="0"),
        sa.Column("platform_keyword_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ads"
    )

    op.create_table("ad_report",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_id", sa.String(36), nullable=False, index=True),
        sa.Column("report_date", sa.DateTime(timezone=True), nullable=False, index=True),
        sa.Column("granularity", sa.String(20), nullable=False, server_default="daily"),
        sa.Column("impressions", sa.Integer, nullable=False, server_default="0"),
        sa.Column("clicks", sa.Integer, nullable=False, server_default="0"),
        sa.Column("spend", sa.Float, nullable=False, server_default="0"),
        sa.Column("sales", sa.Float, nullable=False, server_default="0"),
        sa.Column("orders", sa.Integer, nullable=False, server_default="0"),
        sa.Column("units", sa.Integer, nullable=False, server_default="0"),
        sa.Column("ctr", sa.Float, nullable=False, server_default="0"),
        sa.Column("cpc", sa.Float, nullable=False, server_default="0"),
        sa.Column("acos", sa.Float, nullable=False, server_default="0"),
        sa.Column("roas", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("store_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ads"
    )

    op.create_table("customer",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("customer_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(200), nullable=False, server_default=""),
        sa.Column("email", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("phone", sa.String(50), nullable=False, server_default=""),
        sa.Column("platform", sa.String(50), nullable=False, server_default="", index=True),
        sa.Column("store_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("platform_customer_id", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("country", sa.String(50), nullable=False, server_default=""),
        sa.Column("state", sa.String(100), nullable=False, server_default=""),
        sa.Column("city", sa.String(100), nullable=False, server_default=""),
        sa.Column("address", sa.String(500), nullable=False, server_default=""),
        sa.Column("zip_code", sa.String(30), nullable=False, server_default=""),
        sa.Column("tags_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("segment", sa.String(50), nullable=False, server_default="normal"),
        sa.Column("total_orders", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_order_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("last_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_order_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )

    op.create_table("customer_tag",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("color", sa.String(20), nullable=False, server_default="#1890ff"),
        sa.Column("tag_type", sa.String(30), nullable=False, server_default="manual"),
        sa.Column("auto_rule_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("customer_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )

    op.create_table("customer_communication",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("customer_id", sa.String(36), nullable=False, index=True),
        sa.Column("channel", sa.String(30), nullable=False, server_default="email"),
        sa.Column("direction", sa.String(20), nullable=False, server_default="outbound"),
        sa.Column("subject", sa.String(500), nullable=False, server_default=""),
        sa.Column("content", sa.Text, nullable=False, server_default=""),
        sa.Column("order_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("platform_message_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="sent"),
        sa.Column("handled_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )

    op.create_table("review",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform_review_id", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("order_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("listing_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("customer_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("rating", sa.Integer, nullable=False, server_default="0"),
        sa.Column("title", sa.String(500), nullable=False, server_default=""),
        sa.Column("content", sa.Text, nullable=False, server_default=""),
        sa.Column("reply", sa.Text, nullable=False, server_default=""),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replied_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("is_negative", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("review_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )

    op.create_table("fba_shipment",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipment_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(500), nullable=False, server_default=""),
        sa.Column("platform", sa.String(50), nullable=False, server_default="amazon", index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("fba_shipment_id", sa.String(200), nullable=False, server_default="", index=True),
        sa.Column("destination_fulfillment_center_id", sa.String(50), nullable=False, server_default=""),
        sa.Column("shipment_status", sa.String(30), nullable=False, server_default="draft", index=True),
        sa.Column("shipping_plan_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("box_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_units", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_weight", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("estimated_shipping_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("actual_shipping_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("tracking_no", sa.String(100), nullable=False, server_default=""),
        sa.Column("carrier", sa.String(100), nullable=False, server_default=""),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("remark", sa.Text, nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="fba"
    )

    op.create_table("fba_inventory",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default="amazon"),
        sa.Column("fnsku", sa.String(50), nullable=False, server_default="", index=True),
        sa.Column("asin", sa.String(50), nullable=False, server_default="", index=True),
        sa.Column("fulfillment_center_id", sa.String(50), nullable=False, server_default=""),
        sa.Column("condition_type", sa.String(30), nullable=False, server_default="New"),
        sa.Column("qty_available", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_fulfillable", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_inbound", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_reserved", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_unfulfillable", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_researching", sa.Integer, nullable=False, server_default="0"),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fba"
    )

    op.create_table("fba_fee",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default="amazon"),
        sa.Column("fee_type", sa.String(50), nullable=False, index=True),
        sa.Column("fee_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("fee_date", sa.DateTime(timezone=True), nullable=True, index=True),
        sa.Column("quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("per_unit_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("order_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("raw_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="fba"
    )

    op.create_table("bi_metric",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("metric_code", sa.String(100), nullable=False, index=True),
        sa.Column("metric_name", sa.String(200), nullable=False),
        sa.Column("metric_category", sa.String(50), nullable=False, server_default="general", index=True),
        sa.Column("metric_unit", sa.String(30), nullable=False, server_default=""),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("calculation_sql", sa.Text, nullable=False, server_default=""),
        sa.Column("data_source", sa.String(100), nullable=False, server_default=""),
        sa.Column("refresh_frequency", sa.String(30), nullable=False, server_default="daily"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    )

    op.create_table("bi_metric_value",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("metric_id", sa.String(36), nullable=False, index=True),
        sa.Column("metric_code", sa.String(100), nullable=False, index=True),
        sa.Column("period_type", sa.String(20), nullable=False, server_default="daily"),
        sa.Column("period_date", sa.DateTime(timezone=True), nullable=False, index=True),
        sa.Column("numeric_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("text_value", sa.String(500), nullable=False, server_default=""),
        sa.Column("dimension_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("store_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    )

    op.create_table("bi_report",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("report_code", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("report_type", sa.String(50), nullable=False, server_default="table"),
        sa.Column("category", sa.String(50), nullable=False, server_default="general", index=True),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("query_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("columns_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("filters_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_public", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("owner_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    )

    op.create_table("bi_dashboard_widget",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("dashboard_id", sa.String(36), nullable=False, index=True),
        sa.Column("widget_type", sa.String(50), nullable=False, server_default="metric_card"),
        sa.Column("title", sa.String(200), nullable=False, server_default=""),
        sa.Column("metric_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("metric_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("report_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("layout_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("refresh_interval", sa.Integer, nullable=False, server_default="300"),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    )

    op.create_table("dashboard",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False, index=True),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("layout_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_public", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("owner_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        schema="dashboard"
    )

    op.create_table("dashboard_component",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("dashboard_id", sa.String(36), nullable=False, index=True),
        sa.Column("component_type", sa.String(50), nullable=False, server_default="metric_card"),
        sa.Column("title", sa.String(200), nullable=False, server_default=""),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("data_source", sa.String(100), nullable=False, server_default=""),
        sa.Column("config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("layout_config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("style_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("refresh_interval", sa.Integer, nullable=False, server_default="300"),
        sa.Column("sort_order", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="dashboard"
    )

    op.create_table("dashboard_share",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("dashboard_id", sa.String(36), nullable=False, index=True),
        sa.Column("share_type", sa.String(30), nullable=False, server_default="user"),
        sa.Column("target_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("permission", sa.String(20), nullable=False, server_default="view"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="dashboard"
    )


def downgrade() -> None:
    schemas = ["dashboard", "bi", "fba", "crm", "ads"]
    for schema in schemas:
        op.execute(f"DROP SCHEMA IF EXISTS {schema} CASCADE")
