from alembic import op
import sqlalchemy as sa

revision = "v4_advanced_features"
down_revision = "v3_ads_crm_fba_bi_dashboard"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── SYS: 业务规则版本与执行日志 ──
    op.create_table("biz_rule_version",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_code", sa.String(100), nullable=False, index=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("condition_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("action_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("change_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("changed_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("biz_rule_execution_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_code", sa.String(100), nullable=False),
        sa.Column("rule_type", sa.String(50), nullable=False, index=True),
        sa.Column("rule_version", sa.Integer, nullable=False, server_default="1"),
        sa.Column("context_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("matched", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("action_taken", sa.Text, nullable=False, server_default="{}"),
        sa.Column("explanation", sa.Text, nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    # ── SYS: 跨域业务事件目录 ──
    op.create_table("business_event_catalog",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("event_type", sa.String(200), nullable=False, unique=True, index=True),
        sa.Column("event_name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("aggregate_type", sa.String(100), nullable=False),
        sa.Column("aggregate_action", sa.String(50), nullable=False, server_default="created"),
        sa.Column("event_version", sa.String(10), nullable=False, server_default="v1"),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("payload_schema_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("consumer_domains", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("event_subscription_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("event_type", sa.String(200), nullable=False, index=True),
        sa.Column("subscriber_domain", sa.String(50), nullable=False, index=True),
        sa.Column("subscriber_name", sa.String(200), nullable=False),
        sa.Column("callback_type", sa.String(50), nullable=False, server_default="async"),
        sa.Column("callback_endpoint", sa.String(500), nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    # ── SYS: 连接器SPI框架 ──
    op.create_table("connector_config",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(100), nullable=False, index=True),
        sa.Column("connector_type", sa.String(50), nullable=False, index=True),
        sa.Column("provider", sa.String(100), nullable=False, server_default=""),
        sa.Column("base_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("auth_config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("rate_limit", sa.Integer, nullable=False, server_default="100"),
        sa.Column("timeout", sa.Integer, nullable=False, server_default="30"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.String(20), nullable=False, server_default=""),
        sa.Column("error_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("connector_call_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_code", sa.String(100), nullable=False),
        sa.Column("method", sa.String(10), nullable=False, server_default="GET"),
        sa.Column("path", sa.String(500), nullable=False, server_default=""),
        sa.Column("request_summary", sa.Text, nullable=False, server_default=""),
        sa.Column("response_status", sa.Integer, nullable=False, server_default="0"),
        sa.Column("response_summary", sa.Text, nullable=False, server_default=""),
        sa.Column("is_success", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    # ── SYS: PMS适配器 ──
    op.create_table("pms_recommendation",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("recommendation_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("scene", sa.String(100), nullable=False, server_default=""),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("priority", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("payload_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("evidence_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("erp_reference_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("erp_reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("requires_approval", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("approval_instance_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("execution_log_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("feedback_type", sa.String(20), nullable=False, server_default=""),
        sa.Column("feedback_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("source", sa.String(50), nullable=False, server_default="pms"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("pms_draft",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("draft_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("recommendation_id", sa.String(100), nullable=False, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("draft_type", sa.String(100), nullable=False),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("content_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("erp_reference_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("erp_reference_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    # ── SYS: Webhook回调与重试 ──
    op.create_table("webhook_subscription",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("event_types", sa.Text, nullable=False, server_default="[]"),
        sa.Column("callback_url", sa.String(500), nullable=False),
        sa.Column("secret", sa.String(200), nullable=False, server_default=""),
        sa.Column("http_method", sa.String(10), nullable=False, server_default="POST"),
        sa.Column("headers_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active", index=True),
        sa.Column("max_retries", sa.Integer, nullable=False, server_default="3"),
        sa.Column("retry_interval_seconds", sa.Integer, nullable=False, server_default="60"),
        sa.Column("timeout_seconds", sa.Integer, nullable=False, server_default="30"),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(500), nullable=False, server_default=""),
        sa.Column("consecutive_failures", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    op.create_table("webhook_delivery",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("subscription_id", sa.String(36), nullable=False, index=True),
        sa.Column("event_type", sa.String(200), nullable=False, index=True),
        sa.Column("payload_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("attempt_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("max_attempts", sa.Integer, nullable=False, server_default="3"),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_response_status", sa.Integer, nullable=False, server_default="0"),
        sa.Column("last_response_body", sa.Text, nullable=False, server_default=""),
        sa.Column("last_error", sa.String(500), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    )

    # ── WMS: 库存快照与预警 ──
    op.create_table("inventory_snapshot",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("snapshot_date", sa.String(10), nullable=False, index=True),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("qty_on_hand", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_reserved", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_available", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_inbound", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_outbound", sa.Integer, nullable=False, server_default="0"),
        sa.Column("qty_defective", sa.Integer, nullable=False, server_default="0"),
        sa.Column("cost_price", sa.Float, nullable=False, server_default="0"),
        sa.Column("cost_currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("daily_out_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("avg_daily_out_7d", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_daily_out_30d", sa.Float, nullable=False, server_default="0"),
        sa.Column("days_of_supply", sa.Float, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("inventory_alert_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("alert_type", sa.String(50), nullable=False, index=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("condition_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("warehouse_scope", sa.Text, nullable=False, server_default="[]"),
        sa.Column("sku_scope", sa.Text, nullable=False, server_default="[]"),
        sa.Column("category_scope", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("cooldown_hours", sa.Integer, nullable=False, server_default="24"),
        sa.Column("notify_channels", sa.Text, nullable=False, server_default='["in_app"]'),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("inventory_alert",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(36), nullable=False, index=True),
        sa.Column("alert_type", sa.String(50), nullable=False, index=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("current_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("threshold_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("message", sa.String(500), nullable=False, server_default=""),
        sa.Column("detail_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending", index=True),
        sa.Column("resolved_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(500), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    # ── WMS: 调拨与FBA补货 ──
    op.create_table("stock_transfer_order",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("transfer_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("from_warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("to_warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("items_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("total_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    op.create_table("fba_replenishment_plan",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("plan_no", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("sku_id", sa.String(36), nullable=False, index=True),
        sa.Column("fba_warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("source_warehouse_id", sa.String(36), nullable=False),
        sa.Column("current_fba_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("avg_daily_sales", sa.Float, nullable=False, server_default="0"),
        sa.Column("days_of_supply", sa.Float, nullable=False, server_default="0"),
        sa.Column("suggested_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("approved_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft", index=True),
        sa.Column("strategy_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("strategy_params_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("min_replenishment_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("max_replenishment_qty", sa.Integer, nullable=False, server_default="0"),
        sa.Column("lead_time_days", sa.Integer, nullable=False, server_default="14"),
        sa.Column("safety_stock_days", sa.Integer, nullable=False, server_default="7"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="wms"
    )

    # ── ADS: 智能出价 ──
    op.create_table("bid_adjustment",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("campaign_id", sa.String(36), nullable=False, index=True),
        sa.Column("ad_group_id", sa.String(36), nullable=False, index=True),
        sa.Column("keyword_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("strategy", sa.String(30), nullable=False, server_default="target_acos"),
        sa.Column("current_bid", sa.Float, nullable=False, server_default="0"),
        sa.Column("suggested_bid", sa.Float, nullable=False, server_default="0"),
        sa.Column("applied_bid", sa.Float, nullable=False, server_default="0"),
        sa.Column("target_acos", sa.Float, nullable=False, server_default="0"),
        sa.Column("actual_acos", sa.Float, nullable=False, server_default="0"),
        sa.Column("adjustment_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("is_applied", sa.Boolean, nullable=False, server_default="false", index=True),
        sa.Column("rule_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ads"
    )

    op.create_table("bid_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("strategy", sa.String(30), nullable=False, server_default="target_acos"),
        sa.Column("condition_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("action_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="ads"
    )

    # ── CRM: 客户分群与生命周期 ──
    op.create_table("customer_segment",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("segment_name", sa.String(200), nullable=False),
        sa.Column("segment_code", sa.String(100), nullable=False, index=True),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("segment_type", sa.String(50), nullable=False, server_default="lifecycle"),
        sa.Column("criteria_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("lifecycle_stage", sa.String(30), nullable=False, server_default="", index=True),
        sa.Column("customer_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("avg_order_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_order_frequency", sa.Float, nullable=False, server_default="0"),
        sa.Column("is_auto", sa.Boolean, nullable=False, server_default="false", index=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )

    op.create_table("customer_segment_member",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("segment_id", sa.String(36), nullable=False, index=True),
        sa.Column("customer_id", sa.String(36), nullable=False, index=True),
        sa.Column("lifecycle_stage", sa.String(30), nullable=False, server_default=""),
        sa.Column("rfm_score_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("assigned_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="crm"
    )


def downgrade() -> None:
    for schema, table in [
        ("crm", "customer_segment_member"),
        ("crm", "customer_segment"),
        ("ads", "bid_rule"),
        ("ads", "bid_adjustment"),
        ("wms", "fba_replenishment_plan"),
        ("wms", "stock_transfer_order"),
        ("wms", "inventory_alert"),
        ("wms", "inventory_alert_rule"),
        ("wms", "inventory_snapshot"),
        ("sys", "webhook_delivery"),
        ("sys", "webhook_subscription"),
        ("sys", "pms_draft"),
        ("sys", "pms_recommendation"),
        ("sys", "connector_call_log"),
        ("sys", "connector_config"),
        ("sys", "event_subscription_record"),
        ("sys", "business_event_catalog"),
        ("sys", "biz_rule_execution_log"),
        ("sys", "biz_rule_version"),
    ]:
        op.drop_table(table, schema=schema)
