from alembic import op
import sqlalchemy as sa

revision = "v5_connector_ai_governance"
down_revision = "v4_advanced_features"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("logistics_connector",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_name", sa.String(200), nullable=False),
        sa.Column("connector_code", sa.String(100), nullable=False, index=True),
        sa.Column("carrier_name", sa.String(200), nullable=False),
        sa.Column("carrier_code", sa.String(100), nullable=False, index=True),
        sa.Column("connector_type", sa.String(50), nullable=False, server_default="domestic"),
        sa.Column("api_base_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("auth_type", sa.String(50), nullable=False, server_default="api_key"),
        sa.Column("auth_config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("supported_services_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("supported_label_formats_json", sa.Text, nullable=False, server_default='["pdf"]'),
        sa.Column("supported_origins_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("supported_destinations_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("rate_limit_per_minute", sa.Integer, nullable=False, server_default="60"),
        sa.Column("timeout_seconds", sa.Integer, nullable=False, server_default="30"),
        sa.Column("max_retries", sa.Integer, nullable=False, server_default="3"),
        sa.Column("retry_interval_seconds", sa.Integer, nullable=False, server_default="5"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("health_status", sa.String(30), nullable=False, server_default="unknown"),
        sa.Column("last_health_check_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    
    )

    op.create_table("shipment_label",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipment_id", sa.String(36), nullable=False, index=True),
        sa.Column("tracking_number", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("carrier_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("service_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("label_format", sa.String(20), nullable=False, server_default="pdf"),
        sa.Column("label_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("label_data_base64", sa.Text, nullable=False, server_default=""),
        sa.Column("label_status", sa.String(30), nullable=False, server_default="pending"),
        sa.Column("request_params_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("response_meta_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    
    )

    op.create_table("tracking_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipment_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("tracking_number", sa.String(100), nullable=False, index=True),
        sa.Column("carrier_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("current_status", sa.String(50), nullable=False, server_default="pending", index=True),
        sa.Column("origin_location", sa.String(200), nullable=False, server_default=""),
        sa.Column("destination_location", sa.String(200), nullable=False, server_default=""),
        sa.Column("events_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("estimated_delivery", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_delivery", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exception_code", sa.String(50), nullable=False, server_default=""),
        sa.Column("exception_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    
    )

    op.create_table("freight_quote",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(36), nullable=False, index=True),
        sa.Column("quote_request_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("origin_country", sa.String(10), nullable=False, server_default=""),
        sa.Column("origin_zip", sa.String(20), nullable=False, server_default=""),
        sa.Column("destination_country", sa.String(10), nullable=False, server_default=""),
        sa.Column("destination_zip", sa.String(20), nullable=False, server_default=""),
        sa.Column("weight_grams", sa.Integer, nullable=False, server_default="0"),
        sa.Column("dimensions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("service_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("service_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("carrier_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("estimated_days_min", sa.Integer, nullable=False, server_default="0"),
        sa.Column("estimated_days_max", sa.Integer, nullable=False, server_default="0"),
        sa.Column("freight_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("fuel_surcharge", sa.Float, nullable=False, server_default="0"),
        sa.Column("other_surcharge", sa.Float, nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("quote_response_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_expired", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    
    )

    op.create_table("dispatch_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(36), nullable=False, index=True),
        sa.Column("shipment_id", sa.String(36), nullable=False, index=True),
        sa.Column("batch_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("tracking_number", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("carrier_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("service_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("dispatch_status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("request_params_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("response_meta_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("dispatch_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="tms"
    
    )

    op.create_table("master_data_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("rule_code", sa.String(100), nullable=False, index=True),
        sa.Column("master_data_type", sa.String(50), nullable=False, index=True),
        sa.Column("rule_type", sa.String(50), nullable=False, index=True),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("field_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("condition_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("master_data_issue",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(36), nullable=False, index=True),
        sa.Column("master_data_type", sa.String(50), nullable=False, index=True),
        sa.Column("record_id", sa.String(36), nullable=False, index=True),
        sa.Column("field_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("issue_type", sa.String(50), nullable=False, index=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("message", sa.String(500), nullable=False, server_default=""),
        sa.Column("current_value", sa.String(500), nullable=False, server_default=""),
        sa.Column("expected_value", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="open", index=True),
        sa.Column("resolved_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_note", sa.String(500), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("pms_data_query_policy",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("policy_name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("allowed_scopes", sa.Text, nullable=False, server_default="[]"),
        sa.Column("allowed_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("masked_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("denied_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("row_filter_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("max_rows_per_query", sa.Integer, nullable=False, server_default="1000"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("pms_data_query_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("pms_client_id", sa.String(100), nullable=False, index=True),
        sa.Column("query_domain", sa.String(50), nullable=False, index=True),
        sa.Column("query_scope", sa.String(50), nullable=False, server_default=""),
        sa.Column("query_type", sa.String(50), nullable=False),
        sa.Column("filters_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("requested_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("returned_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("masked_fields", sa.Text, nullable=False, server_default="[]"),
        sa.Column("row_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_success", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("store_authorization",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_name", sa.String(200), nullable=False),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("marketplace_id", sa.String(50), nullable=False, server_default=""),
        sa.Column("seller_id", sa.String(100), nullable=False, server_default=""),
        sa.Column("region", sa.String(10), nullable=False, server_default=""),
        sa.Column("auth_type", sa.String(50), nullable=False, server_default="oauth2"),
        sa.Column("auth_status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("access_token_encrypted", sa.Text, nullable=False, server_default=""),
        sa.Column("refresh_token_encrypted", sa.Text, nullable=False, server_default=""),
        sa.Column("token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("token_scope", sa.String(500), nullable=False, server_default=""),
        sa.Column("auth_meta_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("authorized_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("revoke_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("last_refresh_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_refresh_status", sa.String(30), nullable=False, server_default=""),
        sa.Column("refresh_failure_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("token_refresh_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("store_auth_id", sa.String(36), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False),
        sa.Column("refresh_type", sa.String(30), nullable=False, server_default="auto"),
        sa.Column("is_success", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("old_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("new_token_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("encrypted_secret",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("owner_type", sa.String(50), nullable=False, index=True),
        sa.Column("owner_id", sa.String(36), nullable=False, index=True),
        sa.Column("secret_type", sa.String(50), nullable=False, index=True),
        sa.Column("secret_name", sa.String(200), nullable=False),
        sa.Column("encrypted_value", sa.Text, nullable=False, server_default=""),
        sa.Column("iv", sa.String(100), nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("secret_access_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("secret_id", sa.String(36), nullable=False, index=True),
        sa.Column("owner_type", sa.String(50), nullable=False),
        sa.Column("owner_id", sa.String(36), nullable=False),
        sa.Column("access_type", sa.String(30), nullable=False),
        sa.Column("accessor_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("accessor_ip", sa.String(50), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("import_template",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("template_name", sa.String(200), nullable=False),
        sa.Column("import_type", sa.String(50), nullable=False, index=True),
        sa.Column("columns_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("required_columns_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("validation_rules_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_system", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("import_job",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("template_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("import_type", sa.String(50), nullable=False, index=True),
        sa.Column("file_name", sa.String(500), nullable=False, server_default=""),
        sa.Column("file_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("total_rows", sa.Integer, nullable=False, server_default="0"),
        sa.Column("valid_rows", sa.Integer, nullable=False, server_default="0"),
        sa.Column("invalid_rows", sa.Integer, nullable=False, server_default="0"),
        sa.Column("imported_rows", sa.Integer, nullable=False, server_default="0"),
        sa.Column("failed_rows", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error_summary_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("import_options_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("import_row_error",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("job_id", sa.String(36), nullable=False, index=True),
        sa.Column("row_number", sa.Integer, nullable=False),
        sa.Column("row_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("error_type", sa.String(50), nullable=False),
        sa.Column("error_message", sa.String(500), nullable=False),
        sa.Column("field_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("metric_definition",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("metric_code", sa.String(100), nullable=False, unique=True),
        sa.Column("metric_name", sa.String(200), nullable=False),
        sa.Column("category", sa.String(50), nullable=False, index=True),
        sa.Column("calculation_formula", sa.Text, nullable=False),
        sa.Column("data_type", sa.String(30), nullable=False, server_default="number"),
        sa.Column("unit", sa.String(20), nullable=False, server_default=""),
        sa.Column("supported_dimensions_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("source_tables_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("refresh_frequency", sa.String(30), nullable=False, server_default="daily"),
        sa.Column("is_kpi", sa.Boolean, nullable=False, server_default="false", index=True),
        sa.Column("kpi_target", sa.Float, nullable=False, server_default="0"),
        sa.Column("kpi_target_direction", sa.String(10), nullable=False, server_default="up"),
        sa.Column("owner_domain", sa.String(50), nullable=False, server_default=""),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    
    )

    op.create_table("business_alert",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("alert_name", sa.String(200), nullable=False),
        sa.Column("alert_code", sa.String(100), nullable=False, index=True),
        sa.Column("alert_type", sa.String(50), nullable=False, index=True),
        sa.Column("category", sa.String(50), nullable=False, index=True),
        sa.Column("metric_code", sa.String(100), nullable=False),
        sa.Column("threshold_value", sa.Float, nullable=False),
        sa.Column("threshold_operator", sa.String(10), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("scope_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("notify_channels_json", sa.Text, nullable=False, server_default='["in_app"]'),
        sa.Column("notify_roles_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("cooldown_minutes", sa.Integer, nullable=False, server_default="60"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true", index=True),
        sa.Column("last_triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trigger_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    
    )

    op.create_table("business_alert_instance",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("alert_id", sa.String(36), nullable=False, index=True),
        sa.Column("alert_type", sa.String(50), nullable=False, index=True),
        sa.Column("severity", sa.String(20), nullable=False, server_default="warning"),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("message", sa.Text, nullable=False, server_default=""),
        sa.Column("current_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("threshold_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("metric_code", sa.String(100), nullable=False, server_default=""),
        sa.Column("scope_info_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("suggested_action", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="open", index=True),
        sa.Column("acknowledged_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="bi"
    
    )

    op.create_table("ai_suggestion",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("suggestion_type", sa.String(50), nullable=False, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("source", sa.String(100), nullable=False, server_default="pms"),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False, server_default=""),
        sa.Column("confidence_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("priority", sa.String(20), nullable=False, server_default="medium"),
        sa.Column("status", sa.String(30), nullable=False, server_default="pending", index=True),
        sa.Column("target_entity_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("target_entity_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("suggestion_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("draft_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("execution_result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("feedback_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("rollback_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("pms_suggestion_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("actor_type", sa.String(50), nullable=False, server_default="pms"),
        sa.Column("actor_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("scope", sa.String(100), nullable=False, server_default=""),
        sa.Column("purpose", sa.String(200), nullable=False, server_default=""),
        sa.Column("idempotency_key", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )

    op.create_table("ai_suggestion_execution_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("suggestion_id", sa.String(36), nullable=False, index=True),
        sa.Column("suggestion_type", sa.String(50), nullable=False, index=True),
        sa.Column("domain", sa.String(50), nullable=False, index=True),
        sa.Column("action", sa.String(50), nullable=False),
        sa.Column("action_detail_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_success", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("actor_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys"
    
    )


def downgrade() -> None:
    for schema, table in [
        ("sys", "ai_suggestion_execution_log"),
        ("sys", "ai_suggestion"),
        ("bi", "business_alert_instance"),
        ("bi", "business_alert"),
        ("bi", "metric_definition"),
        ("sys", "import_row_error"),
        ("sys", "import_job"),
        ("sys", "import_template"),
        ("sys", "secret_access_log"),
        ("sys", "encrypted_secret"),
        ("sys", "token_refresh_log"),
        ("sys", "store_authorization"),
        ("sys", "pms_data_query_log"),
        ("sys", "pms_data_query_policy"),
        ("sys", "master_data_issue"),
        ("sys", "master_data_rule"),
        ("tms", "dispatch_record"),
        ("tms", "freight_quote"),
        ("tms", "tracking_record"),
        ("tms", "shipment_label"),
        ("tms", "logistics_connector"),
    ]:
        op.drop_table(table, schema=schema)
