from alembic import op
import sqlalchemy as sa

revision = "v6_middleware_tables"
down_revision = "v5_connector_ai_governance"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS sys")

    op.create_table("notification_template",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("code", sa.String(100), nullable=False, unique=True),
        sa.Column("title_template", sa.String(500), nullable=False),
        sa.Column("body_template", sa.Text, nullable=False),
        sa.Column("channel", sa.String(30), nullable=False, server_default="email"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        schema="sys",
    )

    op.create_table("notification_message",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("template_code", sa.String(100), nullable=False, index=True),
        sa.Column("recipient_id", sa.String(36), nullable=False, index=True),
        sa.Column("title", sa.String(500), nullable=False, server_default=""),
        sa.Column("body", sa.Text, nullable=False, server_default=""),
        sa.Column("channel", sa.String(30), nullable=False, server_default="email"),
        sa.Column("status", sa.String(20), nullable=False, server_default="sent"),
        sa.Column("read_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("file_metadata",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("file_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("original_filename", sa.String(500), nullable=False),
        sa.Column("stored_filename", sa.String(500), nullable=False, server_default=""),
        sa.Column("extension", sa.String(20), nullable=False, server_default=""),
        sa.Column("mime_type", sa.String(100), nullable=False, server_default=""),
        sa.Column("file_size", sa.Integer, nullable=False, server_default="0"),
        sa.Column("is_image", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("is_document", sa.Boolean, nullable=False, server_default="false"),
        sa.Column("domain", sa.String(30), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="uploaded"),
        sa.Column("preview_path", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("workflow_definition",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("flow_code", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("flow_name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(30), nullable=False, server_default=""),
        sa.Column("resource_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("nodes_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("workflow_instance",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("instance_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("definition_id", sa.String(36), nullable=False, index=True),
        sa.Column("flow_code", sa.String(100), nullable=False, index=True),
        sa.Column("business_id", sa.String(100), nullable=False, index=True),
        sa.Column("business_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="running"),
        sa.Column("current_node_id", sa.String(100), nullable=False, server_default=""),
        sa.Column("initiator_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("workflow_task",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("task_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("instance_id", sa.String(100), nullable=False, index=True),
        sa.Column("node_id", sa.String(100), nullable=False),
        sa.Column("node_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("node_type", sa.String(30), nullable=False, server_default="approval"),
        sa.Column("assignee_ids_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("result_comment", sa.String(500), nullable=False, server_default=""),
        sa.Column("completed_by", sa.String(36), nullable=False, server_default=""),
        sa.Column("completed_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("scheduled_job",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("job_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("job_name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(30), nullable=False, server_default=""),
        sa.Column("cron_expression", sa.String(100), nullable=False),
        sa.Column("handler_class", sa.String(200), nullable=False),
        sa.Column("params_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("status", sa.String(20), nullable=False, server_default="active"),
        sa.Column("last_run_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("next_run_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("scheduled_job_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("job_id", sa.String(100), nullable=False, index=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="success"),
        sa.Column("started_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("finished_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("duration_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("result_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("error_message", sa.Text, nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("audit_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("action", sa.String(50), nullable=False, index=True),
        sa.Column("resource_type", sa.String(50), nullable=False, index=True),
        sa.Column("resource_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("resource_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("domain", sa.String(30), nullable=False, server_default="", index=True),
        sa.Column("actor_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("actor_type", sa.String(20), nullable=False, server_default="user"),
        sa.Column("actor_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("before_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("after_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("diff_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("ip_address", sa.String(50), nullable=False, server_default=""),
        sa.Column("user_agent", sa.String(500), nullable=False, server_default=""),
        sa.Column("request_path", sa.String(500), nullable=False, server_default=""),
        sa.Column("request_method", sa.String(10), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="success"),
        sa.Column("error_message", sa.Text, nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("translation_glossary",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("entry_id", sa.String(200), nullable=False, unique=True, index=True),
        sa.Column("domain", sa.String(30), nullable=False, server_default="general"),
        sa.Column("source_term", sa.String(200), nullable=False),
        sa.Column("translations_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("masking_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_code", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("rule_type", sa.String(30), nullable=False, server_default="regex"),
        sa.Column("pattern", sa.String(500), nullable=False, server_default=""),
        sa.Column("replacement", sa.String(200), nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("masking_audit_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_code", sa.String(100), nullable=False, index=True),
        sa.Column("field_name", sa.String(100), nullable=False, server_default=""),
        sa.Column("original_value", sa.String(200), nullable=False, server_default=""),
        sa.Column("masked_value", sa.String(200), nullable=False, server_default=""),
        sa.Column("operator_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("api_endpoint",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("service", sa.String(50), nullable=False, index=True),
        sa.Column("path", sa.String(500), nullable=False),
        sa.Column("method", sa.String(10), nullable=False, server_default="GET"),
        sa.Column("version", sa.String(10), nullable=False, server_default="v1"),
        sa.Column("description", sa.String(500), nullable=False, server_default=""),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("api_call_log",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("service", sa.String(50), nullable=False, index=True),
        sa.Column("path", sa.String(500), nullable=False, index=True),
        sa.Column("method", sa.String(10), nullable=False, server_default="GET"),
        sa.Column("status_code", sa.Integer, nullable=False, server_default="200"),
        sa.Column("response_time_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("caller_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("trace_id", sa.String(36), nullable=False, server_default="", index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("platform_connector",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("connector_type", sa.String(50), nullable=False, index=True),
        sa.Column("connector_name", sa.String(200), nullable=False),
        sa.Column("platform", sa.String(50), nullable=False, index=True),
        sa.Column("version", sa.String(16), nullable=False, server_default="1.0.0"),
        sa.Column("config_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("health_status", sa.String(30), nullable=False, server_default="unknown"),
        sa.Column("last_health_check_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("connector_call_stat",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("connector_id", sa.String(100), nullable=False, index=True),
        sa.Column("success", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("response_time_ms", sa.Integer, nullable=False, server_default="0"),
        sa.Column("error_message", sa.String(500), nullable=False, server_default=""),
        sa.Column("called_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("content_review_task",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("task_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("content_type", sa.String(30), nullable=False),
        sa.Column("content_id", sa.String(100), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("store_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("content_text", sa.Text, nullable=False, server_default=""),
        sa.Column("content_url", sa.String(500), nullable=False, server_default=""),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("auto_result", sa.String(20), nullable=False, server_default=""),
        sa.Column("auto_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("reviewer_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("review_comment", sa.String(500), nullable=False, server_default=""),
        sa.Column("reviewed_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("compliance_check",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("check_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("check_type", sa.String(50), nullable=False),
        sa.Column("resource_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("resource_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("risk_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("violations_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("checked_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="sys",
    )

    op.create_table("forex_rate",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("base_currency", sa.String(10), nullable=False, index=True),
        sa.Column("target_currency", sa.String(10), nullable=False, index=True),
        sa.Column("rate", sa.Float, nullable=False, server_default="0"),
        sa.Column("source", sa.String(50), nullable=False, server_default="ecb"),
        sa.Column("rate_date", sa.String(20), nullable=False, index=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("payment_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("payment_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("order_id", sa.String(100), nullable=False, index=True),
        sa.Column("channel", sa.String(50), nullable=False),
        sa.Column("amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("channel_transaction_id", sa.String(200), nullable=False, server_default=""),
        sa.Column("refund_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("refund_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("billing_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("billing_type", sa.String(30), nullable=False),
        sa.Column("base_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("percentage", sa.Float, nullable=False, server_default="0"),
        sa.Column("tiers_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("cost_event_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("event_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("cost_type", sa.String(50), nullable=False, index=True),
        sa.Column("amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="CNY"),
        sa.Column("sku_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("order_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(100), nullable=False, server_default=""),
        sa.Column("occurred_date", sa.String(20), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("profit_settlement",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("settlement_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("sku_id", sa.String(100), nullable=False, index=True),
        sa.Column("order_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("revenue", sa.Float, nullable=False, server_default="0"),
        sa.Column("purchase_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("head_freight", sa.Float, nullable=False, server_default="0"),
        sa.Column("platform_commission", sa.Float, nullable=False, server_default="0"),
        sa.Column("advertising_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("payment_fee", sa.Float, nullable=False, server_default="0"),
        sa.Column("other_cost", sa.Float, nullable=False, server_default="0"),
        sa.Column("gross_profit", sa.Float, nullable=False, server_default="0"),
        sa.Column("operating_profit", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("period", sa.String(20), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("invoice_record",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("invoice_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("invoice_number", sa.String(100), nullable=False, index=True),
        sa.Column("invoice_type", sa.String(30), nullable=False),
        sa.Column("order_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("customer_name", sa.String(200), nullable=False, server_default=""),
        sa.Column("amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("tax_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("tax_rate", sa.Float, nullable=False, server_default="0"),
        sa.Column("currency", sa.String(10), nullable=False, server_default="USD"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        sa.Column("issue_date", sa.String(20), nullable=False, server_default=""),
        sa.Column("due_date", sa.String(20), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="fms",
    )

    op.create_table("order_strategy_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("rule_type", sa.String(30), nullable=False),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("conditions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("actions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="oms",
    )

    op.create_table("logistics_strategy_rule",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("rule_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("rule_name", sa.String(200), nullable=False),
        sa.Column("rule_type", sa.String(30), nullable=False),
        sa.Column("priority", sa.Integer, nullable=False, server_default="0"),
        sa.Column("conditions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("actions_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="tms",
    )

    op.create_table("cdp_customer_profile",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("profile_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("customer_id", sa.String(100), nullable=False, index=True),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("segment", sa.String(30), nullable=False, server_default="normal"),
        sa.Column("total_orders", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_revenue", sa.Float, nullable=False, server_default="0"),
        sa.Column("avg_order_value", sa.Float, nullable=False, server_default="0"),
        sa.Column("last_order_date", sa.String(20), nullable=False, server_default=""),
        sa.Column("tags_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("attributes_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="crm",
    )

    op.create_table("cdp_behavior_event",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("profile_id", sa.String(100), nullable=False, index=True),
        sa.Column("event_type", sa.String(50), nullable=False, index=True),
        sa.Column("event_data_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("platform", sa.String(50), nullable=False, server_default=""),
        sa.Column("occurred_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="crm",
    )

    op.create_table("selection_analysis",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("analysis_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("category", sa.String(100), nullable=False, server_default=""),
        sa.Column("market", sa.String(50), nullable=False, server_default=""),
        sa.Column("score", sa.Float, nullable=False, server_default="0"),
        sa.Column("demand_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("competition_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("profit_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("trend_score", sa.Float, nullable=False, server_default="0"),
        sa.Column("recommendation", sa.String(20), nullable=False, server_default="neutral"),
        sa.Column("details_json", sa.Text, nullable=False, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="pdm",
    )

    op.create_table("ad_optimization_suggestion",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("suggestion_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("campaign_id", sa.String(100), nullable=False, index=True),
        sa.Column("suggestion_type", sa.String(50), nullable=False),
        sa.Column("current_value", sa.String(200), nullable=False, server_default=""),
        sa.Column("suggested_value", sa.String(200), nullable=False, server_default=""),
        sa.Column("reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="pending"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="ads",
    )

    op.create_table("inventory_voucher",
        sa.Column("id", sa.String(36), primary_key=True),
        sa.Column("tenant_id", sa.String(36), nullable=False, index=True),
        sa.Column("voucher_id", sa.String(100), nullable=False, unique=True, index=True),
        sa.Column("voucher_type", sa.String(50), nullable=False, index=True),
        sa.Column("direction", sa.String(10), nullable=False, server_default="in"),
        sa.Column("warehouse_id", sa.String(36), nullable=False, index=True),
        sa.Column("reference_type", sa.String(50), nullable=False, server_default=""),
        sa.Column("reference_id", sa.String(100), nullable=False, server_default="", index=True),
        sa.Column("lines_json", sa.Text, nullable=False, server_default="[]"),
        sa.Column("total_quantity", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_amount", sa.Float, nullable=False, server_default="0"),
        sa.Column("status", sa.String(20), nullable=False, server_default="draft"),
        sa.Column("operator_id", sa.String(36), nullable=False, server_default=""),
        sa.Column("posted_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("cancelled_at", sa.String(30), nullable=False, server_default=""),
        sa.Column("cancel_reason", sa.String(500), nullable=False, server_default=""),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer, nullable=False, server_default="1"),
        schema="wms",
    )


def downgrade() -> None:
    for schema, table in [
        ("sys", "connector_call_stat"), ("sys", "platform_connector"),
        ("sys", "api_call_log"), ("sys", "api_endpoint"),
        ("sys", "masking_audit_log"), ("sys", "masking_rule"),
        ("sys", "translation_glossary"), ("sys", "audit_log"),
        ("sys", "scheduled_job_log"), ("sys", "scheduled_job"),
        ("sys", "workflow_task"), ("sys", "workflow_instance"),
        ("sys", "workflow_definition"), ("sys", "file_metadata"),
        ("sys", "notification_message"), ("sys", "notification_template"),
        ("sys", "content_review_task"), ("sys", "compliance_check"),
        ("fms", "forex_rate"), ("fms", "payment_record"),
        ("fms", "billing_rule"), ("fms", "cost_event_record"),
        ("fms", "profit_settlement"), ("fms", "invoice_record"),
        ("oms", "order_strategy_rule"), ("tms", "logistics_strategy_rule"),
        ("crm", "cdp_customer_profile"), ("crm", "cdp_behavior_event"),
        ("pdm", "selection_analysis"), ("ads", "ad_optimization_suggestion"),
        ("wms", "inventory_voucher"),
    ]:
        op.drop_table(table, schema=schema)
